In [1]:
import numpy as np

In [2]:
"""
Q.1 - Create a numpy array with 10 elements of the shape(10,1) using np.random
    and find out the mean of the elements using basic numpy functions.
"""
arr = np.random.random([10,1])
print(arr)

[[0.59330448]
 [0.71072314]
 [0.95142162]
 [0.83459771]
 [0.28966059]
 [0.62022649]
 [0.76047548]
 [0.06022066]
 [0.1976497 ]
 [0.63158168]]


In [3]:
#mean
print(np.mean(arr))

0.5649861554762878


In [4]:
"""
Q.2 - Create a numpy array with 20 elements of the shape(20,1) using np.random
        find the variance and standard deviation of the elements.
"""
arr = np.random.random([20,1])
print(arr)

[[0.73765437]
 [0.56624185]
 [0.7277636 ]
 [0.70906126]
 [0.49732093]
 [0.44949337]
 [0.92652007]
 [0.54469126]
 [0.88249116]
 [0.3314408 ]
 [0.22596252]
 [0.87919548]
 [0.90500986]
 [0.45378239]
 [0.59086909]
 [0.39925796]
 [0.94687101]
 [0.01890331]
 [0.66597156]
 [0.77086919]]


In [5]:
#variance
print(np.var(arr))

0.06023287594895752


In [6]:
#standard variance
print(np.std(arr))

0.245423869965734


In [7]:
"""
Q.3 - Create a numpy array A of shape(10,20) and B of shape (20,25) using np.random.
Print the matrix which is the matrix multiplication of A and B.
The shape of the new matrix should be (10,25).
Using basic numpy math functions only find the sum of all the elements of the new matrix.
"""
arr1 = np.random.random([10,20])
print(arr1)

[[0.82832086 0.44854255 0.08956751 0.32253431 0.18950071 0.34583556
  0.68972184 0.79930023 0.03356688 0.84299792 0.03368214 0.66525716
  0.03094695 0.30580174 0.43447183 0.27302702 0.14749531 0.88874176
  0.20493159 0.31530345]
 [0.54836817 0.19575879 0.472795   0.0648617  0.75919438 0.27906174
  0.49756942 0.87247148 0.58334683 0.43198243 0.66926336 0.78324637
  0.92700824 0.82319713 0.87106494 0.99169207 0.01599315 0.09718382
  0.33040367 0.83613568]
 [0.32413593 0.44374855 0.17302477 0.99636645 0.82507539 0.74249794
  0.845499   0.29487955 0.09274005 0.85958529 0.46411295 0.7998215
  0.31122544 0.17986006 0.72504756 0.33179256 0.70456757 0.8099149
  0.69352581 0.64943161]
 [0.68800556 0.3852184  0.55919896 0.47342345 0.17851539 0.15904255
  0.93030993 0.77469613 0.11937238 0.34826485 0.02482889 0.59430737
  0.55844953 0.93199655 0.31325714 0.28135109 0.74053228 0.9033003
  0.75078295 0.89236858]
 [0.37323545 0.63910494 0.78598172 0.69348554 0.26161374 0.52246546
  0.91863562 0.7713

In [8]:
arr2 = np.random.random([20,25])
print(arr2)

[[0.03406668 0.9707954  0.94089562 0.01429588 0.18384939 0.58983526
  0.32729892 0.36319627 0.02747785 0.96622612 0.45463465 0.97875365
  0.32242194 0.78721021 0.11419619 0.01853299 0.18541678 0.56859282
  0.46518222 0.69847424 0.32762472 0.85376366 0.07265948 0.16265246
  0.4735999 ]
 [0.32066466 0.46947663 0.2557603  0.02112868 0.18569867 0.24023809
  0.66810064 0.50880786 0.55548291 0.15744862 0.51799037 0.32826756
  0.9499795  0.14264788 0.78430533 0.21304456 0.28843574 0.16298498
  0.91357439 0.58163843 0.69173922 0.66481814 0.51140103 0.97681744
  0.85936536]
 [0.37486236 0.21837897 0.95084019 0.68997736 0.38433389 0.7729899
  0.88873448 0.60451172 0.15969809 0.06892888 0.54595301 0.68864431
  0.14628022 0.96923922 0.52515273 0.70330869 0.44078723 0.04198044
  0.42923631 0.7602797  0.16099447 0.92926986 0.89219726 0.80614217
  0.46330809]
 [0.27235874 0.75968797 0.91777956 0.82308311 0.90642681 0.56109057
  0.45411038 0.26627996 0.87683635 0.97984296 0.46540134 0.55464327
  0.592

In [9]:
arr = np.matmul(arr1,arr2)
print(arr)

[[3.46422296 3.89085709 3.23170672 2.64293773 3.46646266 3.78472958
  2.81213084 4.15699755 3.19345048 3.47837939 4.1439692  3.98958448
  4.92443976 4.80954039 3.6732067  3.98279716 4.36024642 3.65638528
  3.90520906 3.94215285 4.0345533  4.46728597 3.53980477 3.48450307
  4.06223951]
 [5.11911157 6.70510412 4.3181822  4.69517679 4.10217637 5.28683763
  4.89910813 5.60964357 5.25129157 4.58521697 6.52639561 5.60039109
  6.43203187 6.68768544 5.01794321 5.19633429 6.87193039 5.64284452
  5.16793476 5.03913001 5.19159878 5.01846617 5.30091961 5.91743456
  4.63891441]
 [4.80148391 6.25641727 4.45842691 4.37986192 4.97980888 5.54522676
  4.91546153 4.94993515 5.46465358 5.07655039 6.3333109  5.23196222
  7.11288069 7.48507734 5.2031228  5.85496467 6.88139115 5.75695642
  6.32226062 5.52787057 5.7407555  5.97154123 5.45667586 5.63822435
  5.39294648]
 [4.03445095 5.47708576 4.50045356 4.00061887 4.67532799 5.56978987
  3.8705713  5.79926872 4.34037616 5.05722874 5.82386075 4.49803658
  6.59

In [10]:
#Reshaping
print(np.reshape(arr,(10,25)))

[[3.46422296 3.89085709 3.23170672 2.64293773 3.46646266 3.78472958
  2.81213084 4.15699755 3.19345048 3.47837939 4.1439692  3.98958448
  4.92443976 4.80954039 3.6732067  3.98279716 4.36024642 3.65638528
  3.90520906 3.94215285 4.0345533  4.46728597 3.53980477 3.48450307
  4.06223951]
 [5.11911157 6.70510412 4.3181822  4.69517679 4.10217637 5.28683763
  4.89910813 5.60964357 5.25129157 4.58521697 6.52639561 5.60039109
  6.43203187 6.68768544 5.01794321 5.19633429 6.87193039 5.64284452
  5.16793476 5.03913001 5.19159878 5.01846617 5.30091961 5.91743456
  4.63891441]
 [4.80148391 6.25641727 4.45842691 4.37986192 4.97980888 5.54522676
  4.91546153 4.94993515 5.46465358 5.07655039 6.3333109  5.23196222
  7.11288069 7.48507734 5.2031228  5.85496467 6.88139115 5.75695642
  6.32226062 5.52787057 5.7407555  5.97154123 5.45667586 5.63822435
  5.39294648]
 [4.03445095 5.47708576 4.50045356 4.00061887 4.67532799 5.56978987
  3.8705713  5.79926872 4.34037616 5.05722874 5.82386075 4.49803658
  6.59

In [11]:
#sum of all elements of new matrix
print(np.sum(arr))

1300.836129426879


In [12]:
"""
Q.4 - Create a numpy array A of shape(10,1).Using the basic operations of the numpy array generate an array of shape(10,1)
    such that each element is the following function applied on each element of A. 
    
    f(x)=1 / (1 + exp(-x)) 
    Apply this function to each element of A and print the new array holding the value the function returns
Example:

        a=[a1,a2,a3]   
        n(new array to be printed )=[ f(a1), f(a2), f(a3)]
"""
A = np.random.random([10,1])
print(A)

[[0.14717638]
 [0.67309707]
 [0.18036182]
 [0.25923064]
 [0.71309033]
 [0.90971183]
 [0.15689568]
 [0.95382528]
 [0.01745792]
 [0.39718954]]


In [14]:
import math

In [15]:
def func(x):
    y=1 / (1 + math.exp(-x))
    return y
res=list(map(func,A))
#print(res)
print(np.array(res))

[0.53672782 0.6621963  0.54496862 0.56444716 0.67108365 0.71294119
 0.53914366 0.72188382 0.50436437 0.59801223]
